// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import {ERC721SeaDrop} from "seadrop/ERC721SeaDrop.sol";
import {Base64} from "openzeppelin-contracts/utils/Base64.sol";
import {Strings} from "openzeppelin-contracts/utils/Strings.sol";
import {HoodlingRenderer} from "./HoodlingRenderer.sol";

/// @title HoodlingsDrop
/// @notice SeaDrop-compatible Hoodlings so the primary mint runs natively on
///         OpenSea. 4663 fully on-chain hooded spirits of Robinhood Chain —
///         one for every unit of chain id 4663. Art and metadata are generated
///         entirely inside this contract: no IPFS, no servers.
///
///         Minting goes through OpenSea's SeaDrop protocol (mintSeaDrop);
///         this extension only adds the one-time 163 Founder reserve mint and
///         the fully on-chain tokenURI. Per OpenSea guidance, SeaDrop minting
///         functionality is not modified.
contract HoodlingsDrop is ERC721SeaDrop {
    using Strings for uint256;

    uint256 public constant FOUNDER_SUPPLY = 163;
    bool public foundersMinted;

    error FoundersAlreadyMinted();
    error ExceedsMaxSupply();

    constructor(address[] memory allowedSeaDrop)
        ERC721SeaDrop("Hoodlings", "HOODLING", allowedSeaDrop)
    {}

    /// @notice One-time mint of the 163 Founder Hoodlings (token ids 1-163).
    function mintFounders(address to) external onlyOwner {
        if (foundersMinted) revert FoundersAlreadyMinted();
        foundersMinted = true;
        if (_totalMinted() + FOUNDER_SUPPLY > maxSupply()) revert ExceedsMaxSupply();
        _safeMint(to, FOUNDER_SUPPLY);
    }

    /// @notice Fully on-chain metadata: JSON + SVG generated by the contract.
    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        if (!_exists(tokenId)) revert URIQueryForNonexistentToken();

        string memory svg = HoodlingRenderer.svgOf(tokenId);
        string memory json = string(
            abi.encodePacked(
                '{"name":"Hoodling #', tokenId.toString(),
                '","description":"One of 4663 fully on-chain hooded spirits of Robinhood Chain \\u2014 one for every unit of chain id 4663. Art and metadata live entirely inside the contract. The first 163 are Founder Hoodlings.",',
                '"attributes":', HoodlingRenderer.attributesOf(tokenId),
                ',"image":"data:image/svg+xml;base64,', Base64.encode(bytes(svg)), '"}'
            )
        );
        return string(abi.encodePacked("data:application/json;base64,", Base64.encode(bytes(json))));
    }
}
